// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMI3I8Tn0HScMbbWltL6GbaCrmlVefmJA',
    appId: '1:964732274965:web:ae9a3e1e9745483885c11c',
    messagingSenderId: '964732274965',
    projectId: 'pethaven-321a3',
    authDomain: 'pethaven-321a3.firebaseapp.com',
    storageBucket: 'pethaven-321a3.firebasestorage.app',
    measurementId: 'G-9HPY9YNWYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9GwJRjVCuRGv4gbWIuD561Qhvh8k487U',
    appId: '1:964732274965:android:16079a8aa8f4957485c11c',
    messagingSenderId: '964732274965',
    projectId: 'pethaven-321a3',
    storageBucket: 'pethaven-321a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC4uzQ1st7V0PGIMMwslSWHI-lPyB3Zpg',
    appId: '1:964732274965:ios:e853b1b346436d7785c11c',
    messagingSenderId: '964732274965',
    projectId: 'pethaven-321a3',
    storageBucket: 'pethaven-321a3.firebasestorage.app',
    iosBundleId: 'com.example.petHaven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC4uzQ1st7V0PGIMMwslSWHI-lPyB3Zpg',
    appId: '1:964732274965:ios:e853b1b346436d7785c11c',
    messagingSenderId: '964732274965',
    projectId: 'pethaven-321a3',
    storageBucket: 'pethaven-321a3.firebasestorage.app',
    iosBundleId: 'com.example.petHaven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMI3I8Tn0HScMbbWltL6GbaCrmlVefmJA',
    appId: '1:964732274965:web:49b3b1554d54596f85c11c',
    messagingSenderId: '964732274965',
    projectId: 'pethaven-321a3',
    authDomain: 'pethaven-321a3.firebaseapp.com',
    storageBucket: 'pethaven-321a3.firebasestorage.app',
    measurementId: 'G-FHEESV1KVV',
  );
}
